[30/Nov/2017 12:45:18] "GET / HTTP/1.1" 200 1776
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 202, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 242, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 213, in inner
    if not self.has_permission(request):
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 187, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/utils/functional.py", line 386, in _setup
    self._wrapped = self._setupfunc()
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 210, in get_user
    user_id = _get_user_session_key(request)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 61, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 57, in __getitem__
    return self._session[key]
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 207, in _get_session
    self._session_cache = self.load()
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/contrib/sessions/backends/db.py", line 35, in load
    expire_date__gt=timezone.now()
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 884, in execute_sql
    cursor.execute(sql, params)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_session
[30/Nov/2017 12:45:19] "GET /admin/ HTTP/1.1" 500 192704
[30/Nov/2017 12:45:23] "GET / HTTP/1.1" 200 1776
[30/Nov/2017 12:47:55] "GET /admin/ HTTP/1.1" 302 0
[30/Nov/2017 12:47:55] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1670
[30/Nov/2017 12:47:55] "GET /static/admin/css/base.css HTTP/1.1" 200 16066
[30/Nov/2017 12:47:55] "GET /static/admin/css/login.css HTTP/1.1" 200 1203
[30/Nov/2017 12:47:55] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[30/Nov/2017 12:47:55] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
[30/Nov/2017 12:47:55] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
[30/Nov/2017 12:47:57] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[30/Nov/2017 12:47:58] "GET /admin/ HTTP/1.1" 200 2802
[30/Nov/2017 12:47:58] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
[30/Nov/2017 12:47:58] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[30/Nov/2017 12:47:58] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[30/Nov/2017 12:47:58] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
Performing system checks...

System check identified no issues (0 silenced).

You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
November 30, 2017 - 12:45:12
Django version 1.11.7, using settings 'dkkim.settings'
Starting development server at http://0.0.0.0:33333/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
November 30, 2017 - 12:48:36
Django version 1.11.7, using settings 'dkkim.settings'
Starting development server at http://0.0.0.0:33333/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f16877feea0>
Traceback (most recent call last):
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/bigh2000/public_html/v-dkkim/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/bigh2000/public_html/v-dkkim/dkkim/dkkim/urls.py", line 18, in <module>
    from main.views import show_main
ImportError: cannot import name 'show_main'
Performing system checks...

Performing system checks...

System check identified no issues (0 silenced).
November 30, 2017 - 12:52:47
Django version 1.11.7, using settings 'dkkim.settings'
Starting development server at http://0.0.0.0:33333/
Quit the server with CONTROL-C.
[30/Nov/2017 12:56:20] "GET / HTTP/1.1" 200 14
